export const FieldsUser = [
  {
    'label': 'Prénom',
    'type': 'text',
    'key': 'first_name',
    'order': 1,
    'required': true,
    'controlType': 'textbox',
  },
  {
    'label': 'Nom',
    'type': 'text',
    'key': 'last_name',
    'order': 2,
    'required': true,
    'controlType': 'textbox',
  },
  {
    'label': 'Téléphone ',
    'type': 'number',
    'key': 'phone',
    'order': 3,
    'required': true,
    'controlType': 'textbox',
  },
  {
    'label': 'Adresse',
    'type': 'text',
    'key': 'address',
    'order': 4,
    'required': true,
    'controlType': 'textbox',
  },
  {
    'label': 'Email',
    'type': 'text',
    'key': 'email',
    'order': 5,
    'required': true,
    'controlType': 'textbox',
  },

  {
    'label': 'Structures',
    'type': 'select',
    'key': 'organization_id',
    'url': 'organization',
    'method': 'GET',
    'order': 6,
    'required': true,
    'controlType': 'dropdown',
  },
  {
    'label': 'Profil',
    'type': 'select',
    'key': 'profil_id',
    'url': 'profil',
    'method': 'GET',
    'order': 7,
    'required': true,
    'controlType': 'dropdown',
  },
  {
    'label': 'Mot de passe ',
    'type': 'password',
    'key': 'password',
    'order': 8,
    'required': true,
    'controlType': 'textbox',
  }
]
